### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by kbond** [zenstruck/phpmyadmin-server#3]
- [ ] during init, ask if wanting to use docker
- [ ] ask MySQL version
- [ ] Configure docker-compose.yml
- [ ] `phpmyadmin` command runs `docker compose up -d` before starting
- [ ] `phpmyadmin` command runs `docker compose down` after stopping
- [ ] `phpmyadmin mysql` to run interactive MySQL command

**Comment by kbond** [comment]
```yaml
# docker-compose.yml
version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
```

Run `mysql`: docker compose exec mysql mysql -p1234
